# Application Name
spring.application.name=ashify


spring.data.mongodb.uri=mongodb+srv://tuyubaheashrafu2023:2OTGx7rTmIhCBHwN@ashifextensiondb.7hpss.mongodb.net/AshifExtensionDb?retryWrites=true&w=majority&appName=AshifExtensionDb


spring.data.mongodb.database=AshifExtensionDb


logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
